- name: PLAY-1
  hosts: web
  tasks: 
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "Hello, I am from PLAY-1 and TASK-1"

- name: PLAY-2
  hosts: web
  tasks:
  - name: PLAY-2 and TASK-1
    ansible.builtin.debug:
       msg: "Hello, I am PLAY-2 and TASK-1"