- name: variables
  hosts: localhost
  vars: #variables declaration
    Course: "Ansible"
    Trainer: "Siva"
    Duration: "15hrs"
  tasks: 
  - name: print override information
    vars: # Task level variables
      Course: "DevOps"
      Duration: "120hrs"
    ansible.builtin.debug:
      msg: "Hi. We are learning {{Course}}, from trainer {{Trainer}}, and the Duration is {{Duration}}"

  - name: print override information
    ansible.builtin.debug:
      msg: "Hi. We are learning {{Course}}, from trainer {{Trainer}}, and the Duration is {{Duration}}"
