- name: variables from files
  hosts: web
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}},from Trainer {{Trainer}}, the duration is {{Duration}}"