# If a number is lessthan 10, print lessthan 10 otherwise print greaterthan or equal to 10
- name: localhost
  hosts: localhost
  vars_prompt: #prompts are always considered as text/string
  - name: number
    prompt: please enter number
    private: no
  tasks:
  - name: number is lessthan 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is lessthan 10"
    when: number | int < 10   # Pipe symbol is user for convert the string into int

  - name: number is greaterthan or equal to 10
    ansible.builtin.debug:
      msg: "Given number is {{number}} is greaterthan or equal to 10"
    when: number | int >= 10   # Pipe symbol is user for convert the string into int
