- name: default values
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
   greetings: "Hello, Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

- name: lowercase
  hosts: localhost
  vars:
    greetings: "Hi, GOOD EVENING"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 3, 4, 5, 5, 1]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max values
  hosts: localhost
  vars:
    ages: [12, 22, 27, 35, 55]
  tasks:
  - name: print min and max values
    ansible.builtin.debug:
      msg: "min age: {{ ages | min }}, max age: {{ ages | max }}"