- name: default values
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
   greetings: "Hello, Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

- name: lowercase
  hosts: localhost
  vars:
    greetings: "Hi, GOOD EVENING"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"